
export type UserRole = 'student' | 'teacher' | 'admin' | 'parent';

export type LearningNeed = 'visual_impairment' | 'auditory_impairment' | 'dyslexia' | 'adhd' | 'motor_impairment' | 'autism_spectrum';

export interface TeachingAssignment {
    subject: string;
    grades: string[];
}

export interface UserState {
    id: string;
    role: UserRole;
    name: string;
    email?: string;
    school?: string;
    schoolId?: string; // Links user to a specific school entity
    organization_id?: string; // Production organization link
    status?: 'active' | 'pending' | 'suspended'; // Account status
    currentGrade: string; // Primary grade context
    subject?: string; // Primary subject specialization
    teachingSubjects?: TeachingAssignment[]; // Detailed teaching portfolio
    completedTopics: string[];
    masteredObjectives?: Record<string, string[]>; // Topic ID -> List of Objective IDs
    classId?: string;
    classroom_ids?: string[]; // Production classroom links
    linkedStudentIds?: string[];
    childName?: string;
    linkedStudentId?: string;
    learningNeeds?: LearningNeed[]; // New field for inclusion logic
    parentLinkCode?: string; // Added for parent linking flow
    isDemo?: boolean; // Flag to determine if user is using local mock data or real Supabase data
    ai_credits?: number; // AI Quota system
}

export interface Classroom {
    id: string;
    teacher_id: string;
    join_code: string;
    grade: string;
    subject: string;
    created_at?: string;
}

export interface StudentActivity {
    id: string;
    student_id: string;
    topic_id: string;
    activity_type: string;
    score?: number;
    timestamp: string;
}

export interface Organization {
    id: string;
    name: string;
    ai_quota: number;
    used_quota: number;
}

export interface Topic {
    id: string;
    title: string;
    description: string;
    curriculumStandards?: string[];
    learningObjectives?: string[];
    keyVocabulary?: string[];
    exampleActivities?: string[];
    assessmentFocus?: string[];
    prerequisiteTopicIds?: string[];
    crossCurricularLinks?: {
        subject: string;
        topicId: string;
        description: string;
    }[];
}

export interface Subject {
    name: string;
    topics: Topic[];
}

export interface Grade {
    grade: string;
    subjects: Subject[];
}

export interface Curriculum {
    primary: Grade[];
    highSchool: Grade[];
}

export interface AccessibilitySettings {
    dyslexicFont: boolean;
    highContrast: boolean;
    simplifiedLanguage: boolean;
    autoTranscript: boolean;
    dataSaver: boolean;
}

export type StudyMode = 'intro' | 'deep-dive' | 'exam-prep';

export interface SavedResource {
    id: string;
    title: string;
    type: 'lesson-plan' | 'worksheet' | 'report';
    content: string;
    date: string;
    topicId: string;
    tags?: string[];
}

export interface ChatMessage {
    id: number;
    sender: 'user' | 'ai';
    text: string;
    attachment?: string;
    timestamp: number;
}

export interface QuizQuestion {
    question: string;
    options: string[];
    correctAnswer: number;
    type?: 'text' | 'image-choice' | 'visual-context' | 'true-false';
    explanation?: string;
    imageKeyword?: string;
}

export interface StudentProfile {
    id: string;
    name: string;
    attendance: number;
    averageScore: number;
    riskLevel: 'low' | 'medium' | 'high';
    grade?: string;
    learningNeeds?: LearningNeed[];
}

export interface GradeRecord {
    id: string;
    studentId: string;
    studentName: string;
    itemId: string;
    itemTitle: string;
    score: number;
    total: number;
    type: 'quiz' | 'assignment' | 'battle';
    date: string;
    topicId?: string;
    flagged?: boolean;
    teacherReviewed?: boolean;
    feedback?: string;
}

export interface ScheduleSlot {
    id: string;
    day: string;
    time: string;
    subject: string;
    location?: string;
    type: 'study' | 'class' | 'break' | 'remedial';
    notes?: string;
    autoGenerated?: boolean;
    linkedTopicId?: string;
    grade?: string;
    linkedResourceId?: string; // New: Link directly to a worksheet
    date?: string; // For bulk planning
    status?: 'planned' | 'completed' | 'missed' | 'done' | 'today' | 'upcoming';
}

export interface StudentNotification {
    id: string;
    studentId: string;
    type: 'alert' | 'system' | 'assignment';
    title: string;
    message: string;
    date: string;
    read: boolean;
}

export interface SavedItem {
    id: string;
    type: 'flashcard' | 'lesson' | 'worksheet' | 'unknown' | 'chat';
    title: string;
    date: string;
    data: any;
}

export interface CacheEntry<T> {
    data: T;
    timestamp: number;
    version: number;
}

export interface TermConfig {
    id: string;
    name: string;
    startDate: string;
    endDate: string;
}

export interface MasterSchedule {
    [day: string]: {
        [time: string]: string; // e.g. "08:00": "Mathematics"
    };
}

export interface StudyConstraints {
    schoolStart: string;
    schoolEnd: string;
    preferredStudyStart: string;
    preferredStudyEnd: string;
    studyDays: string[];
    breakTime?: string;
    lunchTime?: string;
    masterSchedule?: MasterSchedule; // New: Recurring timetable
}

export type TopicStatus = 'locked' | 'ready' | 'in-progress' | 'remedial-needed' | 'mastered';

// --- Voice Accessibility Types ---
export type VoiceModeState = 'idle' | 'listening' | 'processing' | 'speaking';
export type VoiceViewType = 'dashboard' | 'journey' | 'lesson' | 'battle' | 'chat' | 'lab';

export interface VoiceCommandResponse {
    spokenText: string;
    action?: 'NAVIGATE' | 'READ_CONTENT' | 'QUIZ_NEXT' | 'REPEAT' | 'EXIT' | 'NONE';
    payload?: any;
}

export type AppView = 
  | 'dashboard' 
  | 'journey' 
  | 'wizard'
  | 'worksheet-generator' // Added
  | 'chat' 
  | 'chalkboard' 
  | 'admin' 
  | 'library' 
  | 'profile' 
  | 'quiz' 
  | 'student-hub'
  | 'student-voice' 
  | 'classroom' 
  | 'admin-users' 
  | 'scheduler' 
  | 'choice-hub' 
  | 'flashcards' 
  | 'audio-lesson' 
  | 'inclusive-quiz' 
  | 'interactive-lesson' 
  | 'accessibility' 
  | 'student-library' 
  | 'admin-curriculum' 
  | 'battle'
  | 'revision-notes'
  | 'bulk-planner-dashboard'
  | 'bulk-unit-creator'
  | 'bulk-reporter';
